---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: check user input (extra variables) existence
      assert:
        that: "{{ item }} is defined"
        msg:  "{{ item }} must be defined as a user input (extra variable)"
      with_items:
        - swname
        - ostype
        - user
        - passwd
        - file_storage

    - name: check file_storage setting
      assert:
        that: "file_storage == 'tftp'"
        msg: "file_storage option is 'tftp'. more to come soon"

    - name: check tftp options if tftp is specified
      assert:
          that: "{{ item }} is defined"
          msg: "{{ item }} must be defined"
      with_items:
        - tftpserver
      when: file_storage == 'tftp'

    - name: check that ostype is correct
      assert:
        that: "ostype == 'ios' or ostype == 'nxos' or ostype == 'eos' or ostype == 'junos'"
        msg: "os type must either be 'ios', 'eos, 'nxos' or 'junos'"

    - name: add switch to inventory on the fly
      add_host:
      args:
        name: "{{ swname }}"
        ansible_host: "{{ swname }}"
        ansible_password: "{{ passwd }}"
        ansible_user: "{{ user }}"
        ansible_network_os: "{{ostype }}"
      no_log: True

- hosts: "{{ swname }}"
  connection: network_cli
  gather_facts: no
  vars:
    ansible_command_timeout: "{{ cmd_timeout | default(999) }}"
  roles:
    - role: showtech
